version: '3'
services:
  # api:
  # web:
  scraper:
    container_name: sneakerheads_scraper
    build:
      context: scraper
      dockerfile: Dockerfile.dev
      args: 
        NODE_ENV: development
    volumes: 
      - ./scraper:/app
    networks: 
      - sneakernet
    # depends_on: 
    #   - redis
    command: bash -c "cd /app && yarn dev"
  # processor:
  # redis:
  #   image: redis:alpine
  #   container_name: sneakerheads_redis
  #   networks:
  #     - sneakernet
networks: 
  sneakernet: