version: '3'
services:
  # api:
  # web:
  scraper:
    container_name: sneakerheads_scraper
    build:
      context: scraper
      dockerfile: Dockerfile.dev
      args: 
        NODE_ENV: development
    volumes: 
      - ./scraper:/app
    networks: 
      - sneakernet
    depends_on: 
      - redis
    command: bash -c "cd /app && yarn dev"
  # processor:
  redis:
    image: redis:alpine
    container_name: sneakerheads_redis
    networks:
      - sneakernet
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
networks: 
  sneakernet: