version: '3'
services:
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sneakerheads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=chris@joyce.dev
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
      - 3000:80